/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


import {
  WeekHeader as WeekHeader
} from './components/zap-datepicker/week-header/week-header';

declare global {
  interface HTMLWeekHeaderElement extends WeekHeader, HTMLElement {
  }
  var HTMLWeekHeaderElement: {
    prototype: HTMLWeekHeaderElement;
    new (): HTMLWeekHeaderElement;
  };
  interface HTMLElementTagNameMap {
    "week-header": HTMLWeekHeaderElement;
  }
  interface ElementTagNameMap {
    "week-header": HTMLWeekHeaderElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "week-header": JSXElements.WeekHeaderAttributes;
    }
  }
  namespace JSXElements {
    export interface WeekHeaderAttributes extends HTMLAttributes {
      date?: any;
      dateRestrictionObj?: any;
      datesObj?: any;
      day?: number;
      daysInMonth?: number;
      lastDay?: number;
      lastDayOfMonth?: any;
      month?: number;
      multidate?: boolean;
      offset?: number;
      selectedDate?: any;
      todaysDate?: string;
      year?: number;
    }
  }
}

