/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


import {
  ZapDatepicker as ZapDatepicker
} from './components/zap-datepicker/zap-datepicker';

declare global {
  interface HTMLZapDatepickerElement extends ZapDatepicker, HTMLElement {
  }
  var HTMLZapDatepickerElement: {
    prototype: HTMLZapDatepickerElement;
    new (): HTMLZapDatepickerElement;
  };
  interface HTMLElementTagNameMap {
    "zap-datepicker": HTMLZapDatepickerElement;
  }
  interface ElementTagNameMap {
    "zap-datepicker": HTMLZapDatepickerElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "zap-datepicker": JSXElements.ZapDatepickerAttributes;
    }
  }
  namespace JSXElements {
    export interface ZapDatepickerAttributes extends HTMLAttributes {
      maxDate?: string;
      minDate?: string;
      multiDate?: boolean;
      zapDatepickerId?: any;
    }
  }
}

